### ISSUE TITLE
异步队列问题的求助 

### ISSUE THREAD

**Issue by medmin** [Barbery/mvc#1]
谢哥，你好，我在v2ex上发了这个帖子，https://www.v2ex.com/t/371186
求助关于pthread和发email的问题
您第一个回复，建议我用异步队列
我这几天折腾下来，发现是一套全新的东西，我本想自学，但折腾好几天，发现还是太慢了
但我这个项目其实催得挺紧，自己学实在来不及了
而且不仅是要发email，还要发短信，所以这个问题肯定要解决

我也试了用ajax，但不能完全达到我的期待。

所以能否请您帮忙，指点一二？如果能给一段示例代码，更是感激不尽！

我用 的是Yii2框架，地址是https://www.github.com/medmin/shineipapp

找不到您的email，所以在这里留言，抱歉。

**Comment by Barbery** [comment]
你好，不用担心，这个其实是一个很简单的东西，队列的实现交给相应的服务来做，你主要做好消费队列的逻辑就OK了，我搜了下，yii2也有不少队列的扩展 例如这个：https://github.com/zhuravljov/yii2-queue   它可以支持多种队列服务，最简单的可以用redis服务来做，也可以选择专业一点的german或者beanstalk来做。
怎么push到队列我就不说了，这个比较简单你可以看文档。消费队列的话，你可以起一个cli的进程，yii也有[console](http://www.yiifans.com/yii2/guide/tutorial-console.html)，伪代码大致是这样：
```
<?php

while(true) {
   # 是否有队列任务需要消费
       # 处理队列任务
   # 否则xx时间后重试（即sleep xx时间）
}
```

这个命令简单一点可以用nohup的方式做成守护进程在后台长期跑，专业一点可以用supervisord来维护

**Comment by medmin** [comment]
谢哥你好，感谢回复！

似乎这个yii2-queue拓展，是封装了一下某些功能，只要装了redis和php-redis，就可以调用yii2-queue的api，把要完成的任务push进去。这个push，算是生产队列。

至于消费队列，就是业务逻辑了，怎么发email，怎么 发短信，或者做一些其他的事。

这个理解对吗？

其实我最大的困惑在于：代码部署到服务器上去之后，还要运行crontab来定时执行？或者按照您说的，使用nohup或者supervisord，这个我的理解是，部署之后，还要进入服务器，写一段script，或者设置一个什么东西，来保证这个消费 队列的执行？

也就是说，异步队列是算是另一个程序了，只是他要听从主程序的吩咐，来做一些事情。

我这样理解对么？

**Comment by Barbery** [comment]
对的，push进队列这一步是在web进程里面触发的，但是消费队列这个是异步的，脱离web服务另外启动的一个进程来消费处理的。所以这个消费者是需要以守护进程的方式持续运行的（就像web服务一样），用crontab可能不太适合。。。

**Comment by medmin** [comment]
非常感谢，我去研究一下。

这个issue能暂时别删吗？可能我还需要回来复习:)

**Comment by Barbery** [comment]
关闭了也是可以查看的，你到close的列表里面找就可以了

**Comment by medmin** [comment]
谢哥你好，又来麻烦您了。

这个文档，写的有点模糊，我即便搜了2天的google，还从头到尾看了一个redis入门视频，还是有个地方没搞明白：
https://github.com/zhuravljov/yii2-queue/blob/master/docs/guide/driver-redis.md
这个文档里，是这样配置的：
return [
    'bootstrap' => [
        'queue', // The component registers own console commands
    ],
    'components' => [
        'queue' => [
            'class' => \zhuravljov\yii\queue\redis\Queue::class,
            'redis' => 'redis', // connection ID
            'channel' => 'queue', // queue channel
        ],
    ],
];

我实在有点晕，connection ID和queue channel是什么？
我猜connection ID是redis的数据库的序号，比如默认是0，最大是15
queue channel是什么就不得而知了，我猜是我写的SendEmail class，但这个猜测估计不对。


能否指点一二？

这问题可能有点蠢，实在抱歉，我实在搜不出来这俩是什么。

**Comment by Barbery** [comment]
这个你应该去作者那里提issue，我很久没用yii了，并不是很清楚哈。我的理解是connection ID是指redis的实例，就是$redis = new Redis()->connect() 的这个，一个可以操作的redis resource，channel的话应该是一个队列名称罢了，给你用来区分不同的队列。

**Comment by medmin** [comment]
哦，已经解决了，昨天刚解决，忘了这边说一下了。

后来发现 是web和console 两个app，都要配置 mailer这个项。

非常感谢您的帮助和推荐这个库！
